name: Generate snake animation

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: generate snake.gif
        uses: Platane/snk@master
        with:
          github_user_name: Lmsilvano
          svg_out_path: dist/snake.gif

      - name: push snake.gif to the output branch
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
